---

- hosts: all
  become: true
  tasks:

#  - name: Update repository index
#    package:
#      update_cache: yes
#      state: latest

  - name: Install apache2 package on Ubuntu
    package:
      name: "{{ apache_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: Install apache2 package on Debian
    package:
      name: "{{ apache_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian"]
