---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
      state: latest

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
