---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Debian)
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: Install updates (Ubuntu)
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: frontend
  become: true
  tasks:

  - name: Install apache2 package on Ubuntu
    apt:
      name:
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: Install apache2 package on Debian
    apt:
      name:
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian"]

  - name: Start apache2 (Debian)
    service:
      name: apache2
      enabled: yes  
      state: started
    register: apache2_status
    when: ansible_distribution in ["Debian"]

  - name: apache2 status
    debug:
      msg: "Apache service is {{ 'started' if apache2_status == 'started' else 'stopped' }}"

  - name: Copy file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: backend
  become: true
  tasks:

  - name: Install MySql on Ubuntu
    apt:
      name:
        - mysql-server
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]

  - name: Install MySql on Debian
    package:
      name:
        - mysql-server
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian"]

